# Step 1: Use the official Python image
FROM python:3.10-slim

# Step 2: Set working directory inside the container
WORKDIR /app

# Step 3: Copy the current directory into the container
COPY . /app

# Step 4: Run the Python script
CMD ["python", "bankingApp.py"]
